(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const control=new URLSearchParams(location.search).get('control')==='1',code=()=>sessionStorage.getItem('schaferOlympicsControlCode')||'';
const COLORS={'Team Red':'#d83b3b','Team Blue':'#3478d4','Team Green':'#2f9b58','Team Gold':'#d4a72c'};
let data=null,selectedRound=1,saving=false;
function pairLabel(p){return `Pair ${p.pairNumber}`}
function barStyle(team){return `--team-bar:${COLORS[team]||'#c7d2df'}`}
function bar(team){return `<span class="team-color-bar" style="${barStyle(team)}" aria-hidden="true"></span>`}
function placeFor(pair,pairs){const order=Number(pair.outOrder);if(!Number.isFinite(order))return null;const ahead=pairs.filter(p=>p.outOrder==null||Number(p.outOrder)>order).length;return ahead+1}
function placeLabel(place){return place===1?'🥇':place===2?'🥈':place===3?'🥉':`${place}.`}
function maxRound(){const nums=(data?.pairs||[]).map(p=>Number(p.outOrder)).filter(Number.isFinite);return Math.max(1,...nums)+1}
function renderRoundPicker(){const host=$('#round-control');if(!host)return;if(!control){host.hidden=true;return}host.hidden=false;host.innerHTML=`<div class="round-picker"><button class="round-step" data-step="-1" type="button" ${selectedRound<=1?'disabled':''}>−</button><div><span>Current round</span><strong>Round ${selectedRound}</strong></div><button class="round-step" data-step="1" type="button">+</button></div><p>Click every pair that gets out in Round ${selectedRound}. You can select multiple pairs in the same round.</p><div id="round-save-state" class="save-state"></div>`;host.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{selectedRound=Math.max(1,selectedRound+Number(b.dataset.step));render()})}
function renderPairs(){const host=$('#pairs'),pairs=data.pairs||[];host.innerHTML=pairs.map(p=>{const out=p.outOrder!=null,active=out&&Number(p.outOrder)===selectedRound,place=placeFor(p,pairs);return `<button type="button" class="pair-card ${control?'pair-card--clickable':''} ${out?'is-out':''} ${active?'is-current-round':''}" style="${barStyle(p.olympicTeam)}" data-id="${esc(p.id)}" ${!control?'disabled':''}>${bar(p.olympicTeam)}<div class="pair-head"><div><div class="pair-name">${esc(pairLabel(p))}</div></div><div class="pair-result">${out?`${placeLabel(place)}<small>Out R${p.outOrder}</small>`:'<span class="still-in">IN</span>'}</div></div><div class="players">${esc([p.player1,p.player2].filter(Boolean).join(' + ')||'Pair not configured')}</div>${control?`<div class="click-hint">${active?`✓ Out in Round ${selectedRound} — click to undo`:out?`Out in Round ${p.outOrder} — click to move to Round ${selectedRound}`:`Click if out in Round ${selectedRound}`}</div>`:''}</button>`}).join('')||'<p>No Egg Toss pairs have been created yet. Set them up in Game Day HQ → Teams.</p>';if(control)bindPairs()}
function renderStandings(){const pairs=[...(data.pairs||[])],scored=pairs.filter(p=>p.outOrder!=null).sort((a,b)=>Number(b.outOrder)-Number(a.outOrder)||a.pairNumber-b.pairNumber);const host=$('#standings');$('#result-note').textContent=!scored.length?'Waiting for results.':data.event?.status==='Complete'?'Final results. Ties share the same place.':'Live results — the first pair out is last place; pairs eliminated in the same round are tied.';host.innerHTML=scored.map(p=>`<div class="stand-row" style="${barStyle(p.olympicTeam)}">${bar(p.olympicTeam)}<div class="medal">${placeLabel(placeFor(p,pairs))}</div><div><strong>${esc(pairLabel(p))}</strong><div>${esc([p.player1,p.player2].filter(Boolean).join(' + '))}</div></div><div class="out-order">Round ${p.outOrder}</div></div>`).join('')||'<p>No pairs are out yet.</p>';const medals=[['🥇',data.event?.goldTeams||[]],['🥈',data.event?.silverTeams||[]],['🥉',data.event?.bronzeTeams||[]]].filter(([,x])=>x.length);if(medals.length)host.insertAdjacentHTML('afterend',`<div class="medal-teams">${medals.map(([m,x])=>`${m} ${x.map(t=>esc(String(t).replace('Team ',''))).join(' + ')}`).join(' &nbsp; • &nbsp; ')}</div>`)}
function render(){document.querySelectorAll('.medal-teams').forEach(x=>x.remove());$('#event-status').textContent=data.event?.status||'Not Started';renderRoundPicker();renderPairs();renderStandings()}
async function post(body){const r=await fetch('/api/egg-toss',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),...body})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save Egg Toss result.');return d}
function bindPairs(){document.querySelectorAll('.pair-card[data-id]').forEach(card=>card.onclick=async()=>{if(saving)return;if(!code()){const s=$('#round-save-state');if(s)s.textContent='Control View is locked.';return}const pair=(data.pairs||[]).find(p=>p.id===card.dataset.id);if(!pair)return;const state=$('#round-save-state');saving=true;card.disabled=true;if(state)state.textContent='Saving…';try{if(pair.outOrder!=null&&Number(pair.outOrder)===selectedRound)data=await post({action:'clear',pairId:pair.id});else data=await post({action:'save',pairId:pair.id,outOrder:selectedRound});if(state)state.textContent='✓ Saved';render()}catch(e){if(state)state.textContent=e.message}finally{saving=false}})}
async function load(){try{const r=await fetch('/api/egg-toss',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load Egg Toss.');data=d;const nums=(data.pairs||[]).map(p=>Number(p.outOrder)).filter(Number.isFinite);selectedRound=nums.length?Math.max(...nums)+1:1;render()}catch(e){$('#pairs').innerHTML=`<p>${esc(e.message)}</p>`}}
load();
})();