(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const control=new URLSearchParams(location.search).get('control')==='1',code=()=>sessionStorage.getItem('schaferOlympicsControlCode')||'';
let data=null;const timers=new Map(),saved=new Map();
function pairLabel(p){return `Pair ${p.pairNumber}`}
function medalFor(order,orders){const unique=[...new Set(orders.filter(Number.isFinite))].sort((a,b)=>b-a);const i=unique.indexOf(order);return i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}.`}
function renderPairs(){const host=$('#pairs'),orders=(data.pairs||[]).map(p=>Number(p.outOrder)).filter(Number.isFinite);host.innerHTML=(data.pairs||[]).map(p=>`<article class="pair-card" data-id="${esc(p.id)}"><div class="pair-head"><div><div class="pair-name">${esc(pairLabel(p))}</div><div class="team">${esc(p.olympicTeam||'No Olympic team')}</div></div><div>${p.outOrder==null?'—':medalFor(Number(p.outOrder),orders)}</div></div><div class="players">${esc([p.player1,p.player2].filter(Boolean).join(' + ')||'Pair not configured')}</div>${control?`<div class="score-control"><label>Out order<input class="out-order-input" type="number" min="1" step="1" inputmode="numeric" value="${p.outOrder??''}" placeholder="1"></label>${p.outOrder!=null?'<button class="btn btn-clear" type="button">Clear</button>':''}</div><div class="save-state"></div>`:`<div class="out-order">Out order: ${p.outOrder??'—'}</div>`}</article>`).join('')||'<p>No Egg Toss pairs have been created yet. Set them up in Game Day HQ → Teams.</p>';if(control)bind()}
function renderStandings(){const pairs=[...(data.pairs||[])],scored=pairs.filter(p=>p.outOrder!=null).sort((a,b)=>Number(b.outOrder)-Number(a.outOrder)||a.pairNumber-b.pairNumber),orders=scored.map(p=>Number(p.outOrder));const host=$('#standings');$('#result-note').textContent=!scored.length?'Waiting for results.':data.event?.status==='Complete'?'Final results. Ties share the same medal.':'Live results — multiple pairs may share an out-order number.';host.innerHTML=scored.map(p=>`<div class="stand-row"><div class="medal">${medalFor(Number(p.outOrder),orders)}</div><div><strong>${esc(pairLabel(p))}</strong><div>${esc([p.player1,p.player2].filter(Boolean).join(' + '))}</div><div class="team">${esc(p.olympicTeam)}</div></div><div class="out-order">#${p.outOrder}</div></div>`).join('')||'<p>No results entered yet.</p>';const medals=[['🥇',data.event?.goldTeams||[]],['🥈',data.event?.silverTeams||[]],['🥉',data.event?.bronzeTeams||[]]].filter(([,x])=>x.length);if(medals.length)host.insertAdjacentHTML('afterend',`<div class="medal-teams">${medals.map(([m,x])=>`${m} ${x.map(t=>esc(String(t).replace('Team ',''))).join(' + ')}`).join(' &nbsp; • &nbsp; ')}</div>`)}
function render(){document.querySelectorAll('.medal-teams').forEach(x=>x.remove());$('#event-status').textContent=data.event?.status||'Not Started';renderPairs();renderStandings()}
async function post(body){const r=await fetch('/api/egg-toss',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),...body})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save Egg Toss result.');return d}
async function saveCard(card,immediate=false){const id=card.dataset.id,input=card.querySelector('.out-order-input'),state=card.querySelector('.save-state'),raw=input.value.trim();if(raw===''){state.textContent='';return}const n=Number(raw);if(!Number.isInteger(n)||n<1){state.textContent='Enter 1 or greater.';return}if(!code()){state.textContent='Control View is locked.';return}if(saved.get(id)===n)return;const run=async()=>{state.textContent='Saving…';try{data=await post({action:'save',pairId:id,outOrder:n});saved.set(id,n);render()}catch(e){state.textContent=e.message}};if(immediate)return run();clearTimeout(timers.get(id));timers.set(id,setTimeout(run,550))}
function bind(){document.querySelectorAll('.pair-card[data-id]').forEach(card=>{const input=card.querySelector('.out-order-input'),clear=card.querySelector('.btn-clear');if(input){input.addEventListener('input',()=>{card.querySelector('.save-state').textContent='Typing…';saveCard(card)});input.addEventListener('change',()=>saveCard(card,true));input.addEventListener('blur',()=>saveCard(card,true))}if(clear)clear.onclick=async()=>{if(!confirm('Clear this pair’s Egg Toss result?'))return;clear.disabled=true;try{data=await post({action:'clear',pairId:card.dataset.id});saved.delete(card.dataset.id);render()}catch(e){card.querySelector('.save-state').textContent=e.message}finally{clear.disabled=false}}})}
async function load(){try{const r=await fetch('/api/egg-toss',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load Egg Toss.');data=d;(data.pairs||[]).forEach(p=>{if(p.outOrder!=null)saved.set(p.id,Number(p.outOrder))});render()}catch(e){$('#pairs').innerHTML=`<p>${esc(e.message)}</p>`}}
load();
})();