(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eventKey=document.body.dataset.eventKey||'',control=new URLSearchParams(location.search).get('control')==='1',code=()=>sessionStorage.getItem('schaferOlympicsControlCode')||'';
let data=null,rosters=[];
const autosaveTimers=new Map(),autosaveState=new Map();
const teamClass={'Team Red':'red','Team Blue':'blue','Team Green':'green','Team Gold':'gold'};
function fmt(sec){if(sec==null||!Number.isFinite(Number(sec)))return '—';const n=Number(sec),m=Math.floor(n/60),s=n-m*60;return `${m}:${s.toFixed(2).padStart(5,'0')}`}
function split(sec){if(sec==null)return{m:'',s:''};const n=Number(sec);return{m:String(Math.floor(n/60)),s:(n%60).toFixed(2)}}
function best(e){const xs=[e.attempt_1_seconds,e.attempt_2_seconds,e.attempt_3_seconds].filter(x=>x!=null).map(Number);return xs.length?Math.min(...xs):null}
function namesFor(team){return rosters.find(r=>r.team===team)?.participants||[]}
function label(e){return e.team_b?`${e.team_a.replace('Team ','')} + ${e.team_b.replace('Team ','')}`:e.team_a||`Entry ${e.entry_number}`}
function renderTeams(){const host=$('#teams');host.innerHTML=(data.entries||[]).map(e=>{const teams=[e.team_a,e.team_b].filter(Boolean);const names=[...new Set(teams.flatMap(namesFor))];return `<article class="team-card"><h3>${esc(label(e))}</h3><p>${e.team_b?'Combined Olympic teams':'Olympic team'}</p>${names.length?`<div class="roster-names">${names.map(n=>`<span>${esc(n)}</span>`).join('')}</div>`:'<p class="muted">No registered players loaded.</p>'}</article>`}).join('')||'<div class="notice">Teams are not configured yet.</div>'}
function attemptRow(e,n){const v=e[`attempt_${n}_seconds`],sp=split(v);if(!control)return `<div class="attempt"><span class="attempt-label">Attempt ${n}</span><span class="time-display">${fmt(v)}</span></div>`;return `<div class="attempt" data-entry="${e.entry_number}" data-attempt="${n}"><span class="attempt-label">Attempt ${n}</span><div class="time-inputs"><input class="mins" type="number" min="0" inputmode="numeric" placeholder="0" value="${esc(sp.m)}"><small>min</small><input class="secs" type="number" min="0" max="59.99" step="0.01" inputmode="decimal" placeholder="0.00" value="${esc(sp.s)}"><small>sec</small></div><div class="attempt-actions"><span class="autosave-note">Autosaves</span>${v!=null?'<button class="btn btn-clear" type="button">Clear</button>':''}</div></div>`}
function renderTrials(){const host=$('#trials');host.innerHTML=(data.entries||[]).map(e=>`<article class="trial-card"><div class="trial-card__head"><div><h3>${esc(label(e))}</h3>${e.team_b?`<div class="team-pair">${esc(e.team_a)} + ${esc(e.team_b)}</div>`:''}</div><span class="best">Best: ${fmt(best(e))}</span></div><div class="attempts">${[1,2,3].map(n=>attemptRow(e,n)).join('')}</div><div class="status" data-status="${e.entry_number}"></div></article>`).join('');if(control)bindTrials()}
function standings(){return [...(data.entries||[])].map(e=>({...e,_best:best(e)})).sort((a,b)=>(a._best??Infinity)-(b._best??Infinity)||a.entry_number-b.entry_number)}
function renderLeaderboard(){const list=standings(),host=$('#leaderboard'),allComplete=list.length>0&&list.every(e=>[e.attempt_1_seconds,e.attempt_2_seconds,e.attempt_3_seconds].every(x=>x!=null)),times=list.map(e=>e._best).filter(x=>x!=null),tie=new Set(times).size!==times.length;$('#final-note').textContent=!times.length?'Waiting for times.':allComplete&&!tie?'Final standings — best of 3 attempts.':tie?'A best-time tie exists. Correct the time or run a tiebreak before finalizing.':'Live standings — best time recorded so far.';host.innerHTML=list.map((e,i)=>`<div class="leader-row"><div class="place">${e._best==null?'—':i===0?'🥇':i===1?'🥈':i===2&&list.length>2?'🥉':`${i+1}.`}</div><div><strong>${esc(label(e))}</strong>${e.team_b?`<div class="team-pair">${esc(e.team_a)} + ${esc(e.team_b)}</div>`:''}</div><div class="leader-time">${fmt(e._best)}</div></div>`).join('')}
function render(){renderTeams();renderTrials();renderLeaderboard();$('#page-status').textContent=data.event?.status||'Not Started';if(control)document.body.classList.add('control')}
async function post(body){const r=await fetch('/api/slip-slide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventKey,code:code(),...body})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save.');return d}
function rowKey(entry,attempt){return `${entry}:${attempt}`}
function parseRow(row){const mRaw=row.querySelector('.mins').value.trim(),sRaw=row.querySelector('.secs').value.trim();if(mRaw===''&&sRaw==='')return{empty:true};const m=Number(mRaw||0),s=Number(sRaw);if(!Number.isFinite(m)||m<0||!Number.isFinite(s)||s<0||s>=60)return{error:'Enter valid minutes and seconds (seconds must be under 60).'};return{seconds:m*60+s}}
async function autosaveRow(row,{immediate=false}={}){const entry=Number(row.dataset.entry),attempt=Number(row.dataset.attempt),key=rowKey(entry,attempt),status=$(`[data-status="${entry}"]`),parsed=parseRow(row);if(parsed.empty){status.textContent='';return}if(parsed.error){status.textContent=parsed.error;return}if(!code()){status.textContent='Control View is locked.';return}const normalized=Number(parsed.seconds.toFixed(2));if(autosaveState.get(key)===normalized)return;const run=async()=>{status.textContent='Saving…';row.classList.add('is-saving');try{await post({action:'saveAttempt',entryNumber:entry,attemptNumber:attempt,seconds:normalized});autosaveState.set(key,normalized);status.textContent='✓ Autosaved';await load()}catch(e){status.textContent=e.message||'Autosave failed.'}finally{row.classList.remove('is-saving')}};if(immediate)return run();clearTimeout(autosaveTimers.get(key));autosaveTimers.set(key,setTimeout(run,650))}
function bindTrials(){document.querySelectorAll('.attempt[data-entry]').forEach(row=>{const clear=row.querySelector('.btn-clear'),entry=Number(row.dataset.entry),attempt=Number(row.dataset.attempt),status=$(`[data-status="${entry}"]`),inputs=[row.querySelector('.mins'),row.querySelector('.secs')];inputs.forEach(input=>{input.addEventListener('input',()=>{status.textContent='Typing…';autosaveRow(row)});input.addEventListener('change',()=>autosaveRow(row,{immediate:true}));input.addEventListener('blur',()=>autosaveRow(row,{immediate:true}))});if(clear)clear.onclick=async()=>{if(!confirm(`Clear attempt ${attempt}?`))return;clear.disabled=true;status.textContent='Clearing…';try{await post({action:'clearAttempt',entryNumber:entry,attemptNumber:attempt});autosaveState.delete(rowKey(entry,attempt));await load();const fresh=$(`[data-status="${entry}"]`);if(fresh)fresh.textContent='Cleared.'}catch(e){status.textContent=e.message}finally{clear.disabled=false}}})}
async function loadRosters(){if(!data?.eventId)return;try{const r=await fetch(`/api/event-rosters?eventId=${encodeURIComponent(data.eventId)}`,{cache:'no-store'}),d=await r.json();if(r.ok)rosters=d.rosters||[]}catch{rosters=[]}}
async function load(){try{const r=await fetch(`/api/slip-slide?eventKey=${encodeURIComponent(eventKey)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load event.');data=d;for(const e of data.entries||[])for(let n=1;n<=3;n++){const v=e[`attempt_${n}_seconds`];if(v!=null)autosaveState.set(rowKey(e.entry_number,n),Number(Number(v).toFixed(2)))}await loadRosters();render()}catch(e){$('#trials').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
load();
})();
