(()=>{
const qs=new URLSearchParams(location.search),control=qs.get('control')==='1',code=()=>sessionStorage.getItem('schaferOlympicsControlCode')||'';
const TEAM_CLASS={'Team Red':'team-red','Team Blue':'team-blue','Team Green':'team-green','Team Gold':'team-gold'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,state={},saving=false;
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
function entries(){return (data?.participants||[]).filter(p=>p.team).map(p=>({id:p.id,label:p.name,team:p.team,teams:[p.team]}))}
function byId(){return new Map((state.entries||[]).map(e=>[e.id,e]))}
function makeOpening(){const groups=new Map();for(const e of shuffle(entries())){if(!groups.has(e.team))groups.set(e.team,[]);groups.get(e.team).push(e)}const pairs=[],left=[];for(const group of groups.values()){while(group.length>=2)pairs.push([group.shift(),group.shift()]);left.push(...group)}const leftovers=shuffle(left);while(leftovers.length>=2)pairs.push([leftovers.shift(),leftovers.shift()]);if(leftovers.length)pairs.push([leftovers.shift(),null]);return pairs}
function roundFromIds(ids){return Array.from({length:Math.ceil(ids.length/2)},(_,i)=>{const a=ids[i*2]||null,b=ids[i*2+1]||null;return{a,b,winner:b?null:a}})}
function generate(){const es=entries();if(es.length<2){$('#message').textContent='At least two registered players with Olympic teams are needed.';return}const opening=makeOpening();state={entries:es,bracketRounds:[opening.map(([a,b])=>({a:a?.id||null,b:b?.id||null,winner:b?null:a?.id||null}))],placements:[],complete:false};$('#message').textContent='Bracket created. Opening matches favor teammate vs teammate whenever possible.';render();save()}
function advance(roundIndex,matchIndex,winnerId){state.bracketRounds[roundIndex][matchIndex].winner=winnerId;state.bracketRounds=state.bracketRounds.slice(0,roundIndex+1);state.placements=[];state.complete=false;let current=state.bracketRounds[roundIndex];if(current.every(m=>m.winner)){const winners=current.map(m=>m.winner).filter(Boolean);if(winners.length===1){const final=current[0],runner=final.a===winnerId?final.b:final.a;const semi=state.bracketRounds[roundIndex-1]||[];const bronze=semi.map(m=>m.a===m.winner?m.b:m.a).filter(Boolean);state.placements=[winnerId,runner,...bronze].filter(Boolean);state.complete=true}else state.bracketRounds.push(roundFromIds(winners))}render();save()}
function playerButton(id,r,m,winner){const e=byId().get(id);if(!e)return '<div class="bye">Bye</div>';return `<button type="button" class="player ${TEAM_CLASS[e.team]||''} ${winner===id?'winner':''}" data-r="${r}" data-m="${m}" data-id="${esc(id)}"><span class="swatch"></span><span><strong>${esc(e.label)}</strong><small>${esc(e.team)}</small></span></button>`}
function renderResults(){const map=byId(),names=['🥇 Gold','🥈 Silver','🥉 Bronze','🥉 Bronze'];const rows=(state.placements||[]).map((id,i)=>{const e=map.get(id);return e?`<div class="result"><span>${names[i]||`${i+1}.`}</span><strong>${esc(e.label)} · ${esc(e.team)}</strong></div>`:''}).join('');$('#results').innerHTML=`<div class="results">${rows||'<p>No final results yet.</p>'}</div>`}
function render(){const es=state.entries||[];$('#status').textContent=data?.event?.status||'Not Started';$('#count').textContent=`${es.length||data?.participants?.length||0} registered players`;$('#generate').hidden=!control;$('#reset').hidden=!control;const rounds=state.bracketRounds||[];$('#bracket').innerHTML=rounds.length?rounds.map((round,r)=>`<section class="round"><h3>${r===rounds.length-1&&round.length===1?'Final':`Round ${r+1}`}</h3><div class="matches">${round.map((m,i)=>`<article class="match"><div class="match-label">Match ${i+1}</div>${m.a?playerButton(m.a,r,i,m.winner):'<div class="bye">Bye</div>'}${m.b?playerButton(m.b,r,i,m.winner):'<div class="bye">Automatic advance</div>'}</article>`).join('')}</div></section>`).join(''):'<p>No bracket yet. Use Random Teammate Bracket to create one.</p>';document.querySelectorAll('.player').forEach(b=>b.onclick=()=>{if(!control)return;advance(Number(b.dataset.r),Number(b.dataset.m),b.dataset.id)});renderResults()}
async function save(){if(!control||saving)return;saving=true;try{const r=await fetch('/api/event-scorecard?eventKey=speed-grab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),action:'save',state})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save bracket.');data=d;state=d.state||state;$('#message').textContent=state.complete?'✓ Speed Grab complete and saved.':'✓ Bracket saved.';render()}catch(e){$('#message').textContent=e.message}finally{saving=false}}
async function reset(){if(!control||!confirm('Reset the entire Speed Grab bracket and results?'))return;try{const r=await fetch('/api/event-scorecard?eventKey=speed-grab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),action:'reset',state:{}})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not reset.');data=d;state={};$('#message').textContent='✓ Speed Grab reset.';render()}catch(e){$('#message').textContent=e.message}}
async function load(){try{const r=await fetch('/api/event-scorecard?eventKey=speed-grab',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load Speed Grab.');data=d;state=d.state||{};const current=new Set((d.participants||[]).map(p=>p.id)),saved=(state.entries||[]).map(e=>e.id),stale=saved.some(id=>!current.has(id))||saved.length&&saved.length!==current.size;if(stale){state={};$('#message').textContent='Registered players changed, so the old bracket was cleared. Create a fresh draw.'}else if(!control)$('#message').textContent='Read-only view';render()}catch(e){$('#message').textContent=e.message}}
$('#generate').onclick=generate;$('#reset').onclick=reset;load();
})();