(()=>{
const TEAMS=['Team Red','Team Blue','Team Green','Team Gold'],STORAGE_KEY='schaferOlympicsControlCode';
const CROSS_TEAM_PAIR_EVENTS=new Set(['egg-toss','cornhole-tournament']);
const tab=document.querySelector('[data-tab="teams"]'),panel=document.querySelector('[data-panel="teams"]'),grid=document.querySelector('#team-editor-grid'),summary=document.querySelector('#team-editor-summary'),message=document.querySelector('#team-editor-message'),saveButton=document.querySelector('#team-editor-save'),balanceButton=document.querySelector('#team-editor-balance'),clearButton=document.querySelector('#team-editor-clear'),filter=document.querySelector('#team-editor-filter');if(!tab||!panel||!grid)return;
let participants=[],events=[],loaded=false,dirty=false,eventEligible=[],eventPairs=[],pendingPick=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const isCornholeKey=k=>String(k||'')==='cornhole-tournament'||String(k||'').toLowerCase()==='cornhole';
const crossTeamPairing=k=>CROSS_TEAM_PAIR_EVENTS.has(String(k||''));
const currentEventKey=()=>document.querySelector('#event-team-select')?.value||'';
const shortTeam=t=>String(t||'').replace('Team ','');
async function api(action,extra={}){const code=sessionStorage.getItem(STORAGE_KEY)||'';if(!code)throw new Error('Control View is locked.');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('/api/admin/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code,...extra}),signal:controller.signal}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){const e=new Error(d.error||'Team editor request failed.');e.data=d;throw e}return d}catch(e){if(e?.name==='AbortError')throw new Error('Team editor request timed out. Refresh and try again.');throw e}finally{clearTimeout(timeout)}}
function setMessage(t,type=''){message.textContent=t||'';message.className='team-editor-message'+(type?` ${type}`:'')}
function counts(){return TEAMS.map(team=>{const people=participants.filter(p=>p.team===team);return{team,total:people.length,men:people.filter(p=>(p.divisions||[]).includes('Man')).length,women:people.filter(p=>(p.divisions||[]).includes('Woman')).length,kids:people.filter(p=>(p.divisions||[]).includes('Kid')).length}})}
function renderSummary(){const assigned=participants.filter(p=>p.team).length;summary.innerHTML=`<div class="team-editor-countline"><strong>${assigned}/${participants.length} assigned</strong><span>${participants.length-assigned} unassigned</span></div><div class="team-editor-cards">${counts().map(c=>`<div class="team-editor-card ${c.team.toLowerCase().replaceAll(' ','-')}"><strong>${esc(shortTeam(c.team))}</strong><span>${c.total}</span><small>${c.men} men · ${c.women} women · ${c.kids} kids</small></div>`).join('')}</div>`}
function render(){renderSummary();const mode=filter?.value||'all',shown=participants.filter(p=>mode==='unassigned'?!p.team:mode==='assigned'?!!p.team:true);grid.innerHTML=shown.length?shown.map(p=>`<div class="team-editor-row" data-key="${esc(p.key)}"><div><strong>${esc(p.name)}</strong><small>${esc((p.divisions||[]).join(' / ')||'—')}</small></div><select><option value="">Unassigned</option>${TEAMS.map(t=>`<option ${p.team===t?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`).join(''):'<div class="team-editor-empty">No participants match this filter.</div>';grid.querySelectorAll('select').forEach(s=>s.onchange=()=>{const p=participants.find(x=>x.key===s.closest('.team-editor-row').dataset.key);if(p)p.team=s.value;dirty=true;setMessage('Unsaved changes','warn');renderSummary()})}
function openPanel(){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('is-active'));document.querySelectorAll('.tab-panel').forEach(p=>{p.hidden=true;p.classList.remove('is-active')});tab.classList.add('is-active');panel.hidden=false;panel.classList.add('is-active');if(!loaded)load()}
function setEventMessage(t,type=''){const e=document.querySelector('#event-team-message');if(e){e.textContent=t||'';e.className='team-editor-message'+(type?` ${type}`:'')}}
function usedKeys(){return new Set(eventPairs.flatMap(p=>[p.member1Key,p.member2Key]).filter(Boolean))}
function personByKey(k){return eventEligible.find(p=>p.key===k)}
function pairTeamLabel(pair){const a=personByKey(pair.member1Key),b=personByKey(pair.member2Key);if(!a&&!b)return'';if(a?.team&&a.team===b?.team)return shortTeam(a.team);return [a?.team,b?.team].filter(Boolean).map(shortTeam).join(' + ')}
function pairingInstructions(){const key=currentEventKey();if(crossTeamPairing(key))return 'Tap any two registered people to make a pair. Mixed Olympic-team pairs are allowed: placement points split 50/50 between their teams; same-team pairs earn the full placement points.';return 'Tap two people from the same Olympic team to make a pair. Used people disappear from the available list.'}
function updatePairingNote(){const note=document.querySelector('#event-pair-note');if(note)note.textContent=pairingInstructions()}
function addPick(key){
  const p=personByKey(key);if(!p)return;
  if(usedKeys().has(key)){setEventMessage('That person is already paired.','error');return}
  if(!pendingPick){pendingPick=key;setEventMessage(crossTeamPairing(currentEventKey())?`Selected ${p.name}. Pick anyone else in this event.`:`Selected ${p.name}. Pick another ${shortTeam(p.team)} teammate.`,'warn');renderEventPairs();return}
  if(pendingPick===key){setEventMessage('Pick a different person for the other half of the pair.','error');return}
  const first=personByKey(pendingPick);
  if(!first){pendingPick=key;renderEventPairs();return}
  if(!crossTeamPairing(currentEventKey())&&first.team!==p.team){pendingPick=key;setEventMessage(`Now select another ${shortTeam(p.team)} teammate.`,'warn');renderEventPairs();return}
  eventPairs.push({id:null,member1Key:pendingPick,member2Key:key,seed:null});pendingPick=null;setEventMessage('Pair added — save when finished.','warn');renderEventPairs();
}
function injectEditor(){
  if(document.querySelector('#event-team-editor'))return;
  const s=document.createElement('section');s.id='event-team-editor';s.className='panel event-team-editor';
  s.innerHTML=`<div class="panel__header panel__header--wrap"><div><p class="section-kicker">Event setup</p><h2>Event Pair Editor</h2><p id="event-pair-note" class="team-editor-note">${esc(pairingInstructions())}</p></div><div class="team-editor-actions"><button id="event-pair-undo" class="refresh" type="button">Undo Last Pair</button><button id="event-pair-clear" class="refresh" type="button">Clear Pairs</button><button id="event-pair-save" class="save-score" type="button">Save Event Pairs</button></div></div><div class="event-team-toolbar"><label><span>Event</span><select id="event-team-select"><option value="">Choose an event…</option></select></label><span id="event-team-message" class="team-editor-message"></span></div><div id="event-team-summary" class="event-team-summary">Choose an event to begin.</div><div id="event-pair-picker"></div><div id="event-pair-grid" class="event-pair-grid"></div><div id="cornhole-seeding"></div>`;panel.appendChild(s);
  const st=document.createElement('style');st.textContent=`.event-team-editor{margin-top:18px}.event-team-toolbar{display:flex;justify-content:space-between;align-items:end;gap:12px;flex-wrap:wrap;margin:16px 0}.event-team-toolbar label{display:grid;gap:6px;min-width:min(100%,360px);font-size:.82rem;font-weight:850}.event-team-toolbar select,.seed-row select{min-height:42px;padding:8px 10px;border:1px solid #cbd7e4;border-radius:9px;background:#fff;font:inherit}.event-team-summary{padding:11px 13px;background:#f5f8fc;border-radius:11px;color:#65758a;font-size:.9rem}.pair-team{margin:14px 0;border:1px solid #dbe3ed;border-radius:13px;overflow:hidden}.pair-team h3{margin:0;padding:10px 12px;background:#f5f8fc;font-size:.9rem}.pair-people{display:flex;gap:8px;flex-wrap:wrap;padding:10px}.pair-person{border:1px solid #cbd7e4;background:#fff;border-radius:999px;padding:9px 12px;font-weight:800;cursor:pointer}.pair-person.selected{outline:3px solid #345b82}.pair-team-empty{padding:10px 12px;color:#7a8797;font-size:.85rem}.event-pair-grid{display:grid;gap:8px;margin-top:12px}.event-pair{display:flex;align-items:center;gap:9px;flex-wrap:wrap;padding:11px 12px;border:1px solid #dbe3ed;border-radius:12px}.event-pair strong{min-width:58px}.event-pair__team{font-size:.78rem;font-weight:900;padding:5px 8px;border-radius:999px;background:#eef3f8}.event-pair__remove{margin-left:auto;border:0;background:#f5f8fc;border-radius:9px;padding:8px 10px;font-weight:850;cursor:pointer}.cornhole-seeding{margin-top:20px;padding-top:18px;border-top:2px solid #e5ebf2}.seed-grid{display:grid;gap:8px;margin:12px 0}.seed-row{display:grid;grid-template-columns:75px 1fr;align-items:center;gap:10px}.seed-row strong{font-size:.9rem}.seed-warning{padding:10px 12px;border-radius:10px;background:#fff7e8;margin:10px 0;font-size:.88rem}.seed-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}.seed-save{margin-top:0}.seed-actions .team-editor-message{flex:1 1 220px}@media(max-width:650px){.seed-row{grid-template-columns:65px 1fr}.pair-person{padding:11px 13px}.event-pair__remove{margin-left:0}.seed-actions button{width:100%}}`;document.head.appendChild(st);
  const sel=s.querySelector('#event-team-select');sel.innerHTML='<option value="">Choose an event…</option>'+events.map(e=>`<option value="${esc(e.key)}">#${e.number??'–'} ${esc(e.name)}</option>`).join('');sel.onchange=loadEventPairs;
  s.querySelector('#event-pair-undo').onclick=()=>{if(pendingPick)pendingPick=null;else eventPairs.pop();setEventMessage('Unsaved event pair changes','warn');renderEventPairs()};
  s.querySelector('#event-pair-clear').onclick=async()=>{if(!sel.value||!confirm('Clear all saved pairs for this event?'))return;try{await api('saveEventPairs',{eventKey:sel.value,pairs:[]});eventPairs=[];pendingPick=null;setEventMessage('✓ Event pairs cleared','success');renderEventPairs()}catch(e){setEventMessage(e.message,'error')}};
  s.querySelector('#event-pair-save').onclick=saveEventPairs;
}
function renderEventPairs(){
  const box=document.querySelector('#event-pair-grid'),picker=document.querySelector('#event-pair-picker'),sum=document.querySelector('#event-team-summary');if(!box||!picker||!sum)return;
  updatePairingNote();
  const used=usedKeys(),remaining=eventEligible.length-used.size;
  sum.innerHTML=`<strong>${used.size}/${eventEligible.length} matched</strong> · ${remaining} remaining · ${eventPairs.length} pair${eventPairs.length===1?'':'s'}${isCornholeKey(currentEventKey())?` · <strong>${eventPairs.length}/14 Cornhole teams</strong>`:''}`;
  picker.innerHTML=TEAMS.map(team=>{const people=eventEligible.filter(p=>p.team===team&&!used.has(p.key)),selected=pendingPick&&personByKey(pendingPick)?.team===team?pendingPick:null;return `<div class="pair-team"><h3>${esc(team)} — ${people.length} available</h3>${people.length?`<div class="pair-people">${people.map(p=>`<button type="button" class="pair-person ${selected===p.key?'selected':''}" data-key="${esc(p.key)}">${esc(p.name)}</button>`).join('')}</div>`:'<div class="pair-team-empty">Everyone on this team is matched.</div>'}</div>`}).join('');
  picker.querySelectorAll('.pair-person').forEach(b=>b.onclick=()=>addPick(b.dataset.key));
  box.innerHTML=eventPairs.length?eventPairs.map((p,i)=>{const a=personByKey(p.member1Key),b=personByKey(p.member2Key);return `<div class="event-pair"><strong>Pair ${i+1}</strong><span>${esc(a?.name||'')}</span><span>+</span><span>${esc(b?.name||'')}</span><span class="event-pair__team">${esc(pairTeamLabel(p))}</span><button type="button" class="event-pair__remove" data-i="${i}">Remove</button></div>`}).join(''):`<div class="pair-team-empty">No pairs yet. ${crossTeamPairing(currentEventKey())?'Tap any two registered people above.':'Tap two teammates above.'}</div>`;
  box.querySelectorAll('.event-pair__remove').forEach(b=>b.onclick=()=>{eventPairs.splice(Number(b.dataset.i),1);pendingPick=null;setEventMessage('Unsaved event pair changes','warn');renderEventPairs()});renderSeeding();
}
async function loadEventPairs(){
  const sel=document.querySelector('#event-team-select'),key=sel?.value||'';eventEligible=[];eventPairs=[];pendingPick=null;setEventMessage('');updatePairingNote();
  if(!key){document.querySelector('#event-pair-picker').innerHTML='';document.querySelector('#event-pair-grid').innerHTML='';document.querySelector('#cornhole-seeding').innerHTML='';document.querySelector('#event-team-summary').textContent='Choose an event to begin.';return}
  try{const d=await api('eventPairs',{eventKey:key});eventEligible=d.eligible||[];eventPairs=(d.pairs||[]).map(p=>({id:p.id,member1Key:p.member1Key,member2Key:p.member2Key,seed:p.seed||null}));renderEventPairs()}catch(e){setEventMessage(e.message,'error')}
}
async function saveEventPairs(){const sel=document.querySelector('#event-team-select'),btn=document.querySelector('#event-pair-save');if(!sel?.value)return;if(pendingPick){setEventMessage('Finish the selected pair first.','error');return}btn.disabled=true;try{await api('saveEventPairs',{eventKey:sel.value,pairs:eventPairs});await loadEventPairs();setEventMessage(`✓ ${eventPairs.length} pair${eventPairs.length===1?'':'s'} saved`,'success')}catch(e){setEventMessage(e.message,'error')}finally{btn.disabled=false}}
function renderSeeding(){
  const host=document.querySelector('#cornhole-seeding'),sel=document.querySelector('#event-team-select');if(!host)return;if(!isCornholeKey(sel?.value)){host.innerHTML='';return}
  if(eventPairs.length!==14){host.innerHTML=`<div class="cornhole-seeding"><h3>14-Team Cornhole Seeding</h3><p>Save exactly 14 Cornhole pairs first. Current pairs: <strong>${eventPairs.length}/14</strong>.</p></div>`;return}
  if(eventPairs.some(p=>!p.id)){host.innerHTML='<div class="cornhole-seeding"><h3>14-Team Cornhole Seeding</h3><p>Save the Cornhole pairs first, then assign seeds.</p></div>';return}
  const sorted=[...eventPairs].sort((a,b)=>(a.seed||99)-(b.seed||99));
  host.innerHTML=`<div class="cornhole-seeding"><p class="section-kicker">Control View only</p><h3>14-Team Cornhole Seeding</h3><p class="team-editor-note">Assign Seeds 1–14 manually or use Random Seed. The six preliminary games reduce the field to an 8-team winners bracket.</p><div class="seed-grid">${Array.from({length:14},(_,i)=>{const seed=i+1,p=sorted.find(x=>x.seed===seed);return `<label class="seed-row"><strong>Seed ${seed}</strong><select data-seed="${seed}"><option value="">Choose pair…</option>${eventPairs.map((x,j)=>{const a=personByKey(x.member1Key),b=personByKey(x.member2Key);return `<option value="${esc(x.id)}" ${p?.id===x.id?'selected':''}>Pair ${j+1}: ${esc(a?.name||'')} + ${esc(b?.name||'')} (${esc(pairTeamLabel(x))})</option>`}).join('')}</select></label>`}).join('')}</div><div class="seed-warning">If Cornhole has already started, reseeding requires confirmation and resets all Cornhole match results.</div><div class="seed-actions"><button id="cornhole-seed-random" class="refresh" type="button">🎲 Random Seed</button><button id="cornhole-seed-save" class="save-score seed-save" type="button">Save & Seed 14-Team Bracket</button><span id="cornhole-seed-message" class="team-editor-message"></span></div></div>`;
  host.querySelector('#cornhole-seed-random').onclick=randomizeSeeds;host.querySelector('#cornhole-seed-save').onclick=saveSeeds;
}
function randomizeSeeds(){const selects=[...document.querySelectorAll('.seed-row select')],randomPairs=shuffle(eventPairs);selects.forEach((s,i)=>{s.value=randomPairs[i]?.id||''});const msg=document.querySelector('#cornhole-seed-message');if(msg)msg.textContent='🎲 Random draw ready — press Save & Seed 14-Team Bracket.'}
async function saveSeeds(){const selects=[...document.querySelectorAll('.seed-row select')],ids=selects.map(s=>s.value);if(selects.length!==14||ids.some(x=>!x)||new Set(ids).size!==14){document.querySelector('#cornhole-seed-message').textContent='Choose each of the 14 pairs exactly once.';return}const seeds=selects.map(s=>({seed:Number(s.dataset.seed),pairId:s.value})),btn=document.querySelector('#cornhole-seed-save'),msg=document.querySelector('#cornhole-seed-message');btn.disabled=true;try{let d;try{d=await api('seedCornhole',{seeds,forceReset:false})}catch(e){if(e.data?.needsResetConfirmation){if(!confirm('Cornhole already has scores/results. Reseeding will RESET the entire Cornhole bracket. Continue?'))return;d=await api('seedCornhole',{seeds,forceReset:true})}else throw e}msg.textContent=`✓ 14-team bracket seeded`;const fresh=await api('eventPairs',{eventKey:'cornhole-tournament'});eventPairs=(fresh.pairs||[]).map(p=>({id:p.id,member1Key:p.member1Key,member2Key:p.member2Key,seed:p.seed||null}));renderEventPairs();document.querySelector('#cornhole-seed-message').textContent='✓ 14-team bracket seeded'}catch(e){msg.textContent=e.message}finally{btn.disabled=false}}
async function load(){loaded=true;grid.innerHTML='<div class="team-editor-empty">Loading participants…</div>';try{const d=await api('list');participants=d.participants||[];events=d.events||[];dirty=false;render();injectEditor()}catch(e){loaded=false;grid.innerHTML=`<div class="team-editor-empty error-text">${esc(e.message)}</div>`;setMessage(e.message,'error')}}
function balancedAssignments(){const groups=new Map(),totals=Object.fromEntries(TEAMS.map(t=>[t,0]));participants.forEach(p=>{const k=(p.divisions||[]).slice().sort().join('|')||'Other';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p)});for(const people of groups.values())shuffle(people).forEach(p=>{const low=Math.min(...TEAMS.map(t=>totals[t])),choices=shuffle(TEAMS.filter(t=>totals[t]===low));p.team=choices[0];totals[p.team]++})}
tab.addEventListener('click',openPanel);filter?.addEventListener('change',render);balanceButton?.addEventListener('click',()=>{if(participants.length&&confirm('Auto-balance everyone? Changes are only a draft until Save Teams.')){balancedAssignments();dirty=true;setMessage('Balanced draft ready — press Save Teams.','warn');render()}});clearButton?.addEventListener('click',()=>{if(participants.length&&confirm('Set every participant to Unassigned?')){participants.forEach(p=>p.team='');dirty=true;setMessage('All unassigned in draft — press Save Teams.','warn');render()}});saveButton?.addEventListener('click',async()=>{saveButton.disabled=true;try{await api('save',{assignments:participants.map(p=>({participantKey:p.key,team:p.team||''}))});dirty=false;setMessage('✓ Teams saved','success');renderSummary();if(document.querySelector('#event-team-select')?.value)await loadEventPairs()}catch(e){setMessage(e.message,'error')}finally{saveButton.disabled=false}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
})();
