import base from './worker.js';

const TEAMS=['Team Red','Team Blue','Team Green','Team Gold'];
const SOCCER_EVENT_ID='3cbb6690-280e-80ca-a504-f8137aedee4e';
const WIFFLE_EVENT_ID='e3ff5917-7897-44da-b0a4-a78816bfb46c';
const NOTION_VERSION='2026-03-11';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const arr=v=>(Array.isArray(v)?v:v?[v]:[]).filter(x=>TEAMS.includes(x));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const propTeams=names=>({multi_select:names.map(name=>({name}))});
async function patchPage(id,properties,env){const r=await fetch(`https://api.notion.com/v1/pages/${encodeURIComponent(id)}`,{method:'PATCH',headers:{Authorization:`Bearer ${env.NOTION_API_TOKEN}`,'Notion-Version':NOTION_VERSION,'Content-Type':'application/json'},body:JSON.stringify({properties})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Notion rejected update');return d}
function bronze1(p){const v=arr(p['Bronze 1 Team']);return v.length?v:arr(p['🥉 Team'])}
function bronze1Points(p){return p['Bronze 1 Points']!=null?num(p['Bronze 1 Points']):num(p['🥉 Bronze Points'])}
function standings(rows){const points=Object.fromEntries(TEAMS.map(t=>[t,0]));for(const row of rows){const p=row.properties||{};for(const t of arr(p['🥇 Team']))points[t]+=num(p['🥇 Gold Points']);for(const t of arr(p['🥈 Team']))points[t]+=num(p['🥈 Silver Points']);for(const t of bronze1(p))points[t]+=bronze1Points(p);for(const t of arr(p['Bronze 2 Team']))points[t]+=num(p['Bronze 2 Points'])}return TEAMS.map(team=>({team,points:points[team]})).sort((a,b)=>b.points-a.points)}
async function scores(request,env){const response=await base.fetch(request,env);const data=await response.json();if(!response.ok||data.error)return json(data,response.status);const s=standings(data.rows||[]);const remaining=num(data.race?.remainingGoldPoints);data.standings=s;data.race={...(data.race||{}),maximumPossible:s.map(x=>({team:x.team,currentPoints:x.points,maximumPoints:x.points+remaining}))};return json(data)}
async function admin(request,env){if(!env.NOTION_API_TOKEN||!env.ADMIN_SCORE_CODE)return json({error:'Score entry runtime secrets are missing.'},503);let b;try{b=await request.json()}catch{return json({error:'Invalid request.'},400)}if(String(b.code||'')!==String(env.ADMIN_SCORE_CODE))return json({error:'Incorrect score-entry code.'},401);const id=String(b.eventId||'');if(!id)return json({error:'Choose an event.'},400);try{if(b.action==='clear'){await patchPage(id,{'🥇 Team':propTeams([]),'🥈 Team':propTeams([]),'Bronze 1 Team':propTeams([]),'Bronze 2 Team':propTeams([]),'🥉 Team':propTeams([]),Status:{status:{name:'Not Started'}}},env);return json({ok:true,cleared:true})}const gold=arr(b.goldTeams??b.goldTeam),silver=arr(b.silverTeams??b.silverTeam),b1=arr(b.bronze1Teams??b.bronze1Team),b2=arr(b.bronze2Teams??b.bronze2Team),two=Boolean(b.isTwoTeam),status=['Not Started','In Progress','Delayed','Complete'].includes(b.status)?b.status:'Complete';if(!gold.length||!silver.length)return json({error:'Choose gold and silver teams.'},400);if(two&&(gold.length!==2||silver.length!==2||b1.length||b2.length))return json({error:'Two-team events require exactly two Gold teams, two Silver teams, and no Bronze teams.'},400);if(!two&&(gold.length!==1||silver.length!==1||b1.length>1||b2.length>1))return json({error:'Normal events use one team per finishing position.'},400);const all=[...gold,...silver,...b1,...b2];if(new Set(all).size!==all.length)return json({error:'A team cannot occupy more than one finishing position.'},400);await patchPage(id,{'🥇 Team':propTeams(gold),'🥈 Team':propTeams(silver),'Bronze 1 Team':propTeams(b1),'Bronze 2 Team':propTeams(b2),'🥉 Team':propTeams([]),Status:{status:{name:status}}},env);return json({ok:true,status})}catch(e){return json({error:e.message},502)}}
function fourFinish(matches=[]){const props=code=>(matches.find(m=>m.properties?.Match===code)?.properties||{}),finish=props('F'),bronze=props('B');return{bronze:bronze.Status==='Complete'?String(bronze.Winner||''):'',copper:bronze.Status==='Complete'?String(bronze.Loser||''):'',gold:finish.Status==='Complete'?String(finish.Winner||''):'',silver:finish.Status==='Complete'?String(finish.Loser||''):''}}
async function tournament(request,env,eventId,ctx){const response=await base.fetch(request,env);let data;try{data=await response.clone().json()}catch{return response}if(response.ok&&env.NOTION_API_TOKEN){let finish={bronze:data?.medals?.bronze||'',copper:data?.medals?.copper||''};try{const url=new URL(request.url);const getReq=new Request(url.toString(),{method:'GET',headers:request.headers});const fresh=await base.fetch(getReq,env);if(fresh.ok){const d=await fresh.json();finish=fourFinish(d.matches||[])}}catch(e){console.error('Four-team finish lookup failed',e)}if(request.method==='POST'||finish.bronze||finish.copper){const sync=patchPage(eventId,{'Bronze 1 Team':propTeams(finish.bronze?[finish.bronze]:[]),'Bronze 2 Team':propTeams(finish.copper?[finish.copper]:[])},env).catch(e=>console.error('Bronze/copper sync failed',e));if(ctx?.waitUntil)ctx.waitUntil(sync);else await sync}if(data.medals){data.medals={...data.medals,bronze:finish.bronze||null,copper:finish.copper||null}}}return response.ok&&data?json(data,response.status):response}
export default{async fetch(request,env,ctx){const path=new URL(request.url).pathname;if(path==='/api/scores'&&request.method==='GET')return scores(request,env);if(path==='/api/admin/scores'&&request.method==='POST')return admin(request,env);if(path==='/api/adult-soccer')return tournament(request,env,SOCCER_EVENT_ID,ctx);if(path==='/api/wiffle-ball')return tournament(request,env,WIFFLE_EVENT_ID,ctx);return base.fetch(request,env)}};
