const NOTION_VERSION="2026-03-11";
const DEFAULT_DATA_SOURCE_ID="1bffd4df-3de3-4e8e-9c13-cbcb1e30e226";
const PARTICIPANTS_ID="cb8b3ac0-2a7e-42cc-ba24-a6de0121ffd5";
const CORNHOLE_ID="1894a90f-2b0c-440f-90de-7274384e379c";
const TEAMS=["Team Red","Team Blue","Team Green","Team Gold"];
const EVENT_STATUSES=["Not Started","In Progress","Delayed","Complete"];

function json(data,init={}){const h=new Headers(init.headers||{});h.set("Content-Type","application/json; charset=utf-8");h.set("Cache-Control","no-store");return new Response(JSON.stringify(data),{...init,headers:h})}
function plainText(p=[]){return p.map(x=>x?.plain_text??x?.text?.content??"").join("")}
function norm(p){if(!p)return null;switch(p.type){case"title":return plainText(p.title);case"rich_text":return plainText(p.rich_text);case"number":return p.number;case"select":return p.select?.name??null;case"status":return p.status?.name??null;case"checkbox":return p.checkbox;case"date":return p.date?.start??null;case"formula":return p.formula?.[p.formula.type]??null;case"multi_select":return p.multi_select?.map(x=>x.name)??[];case"relation":return p.relation?.map(x=>x.id)??[];default:return null}}
function page(x){const properties={};for(const[n,p]of Object.entries(x.properties||{}))properties[n]=norm(p);return{id:x.id,lastEditedTime:x.last_edited_time,properties}}
function ds(v){return String(v||DEFAULT_DATA_SOURCE_ID).trim().replace(/^collection:\/\//i,"")}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function teams(v){return(Array.isArray(v)?v:v?[v]:[]).filter(x=>TEAMS.includes(x))}
function complete(r){return r.properties?.Status==="Complete"}
const rt=s=>({rich_text:s?[{type:"text",text:{content:String(s)}}]:[]});

async function queryAll(token,id){const out=[];let cursor;do{const r=await fetch(`https://api.notion.com/v1/data_sources/${encodeURIComponent(id)}/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Notion-Version":NOTION_VERSION,"Content-Type":"application/json"},body:JSON.stringify({page_size:100,...(cursor?{start_cursor:cursor}:{})})}),d=await r.json();if(!r.ok){const e=new Error(d.message||`Notion ${r.status}`);e.status=r.status;e.code=d.code;throw e}out.push(...(d.results||[]));cursor=d.has_more?d.next_cursor:null}while(cursor);return out}
async function patch(id,properties,env){const r=await fetch(`https://api.notion.com/v1/pages/${encodeURIComponent(id)}`,{method:"PATCH",headers:{Authorization:`Bearer ${env.NOTION_API_TOKEN}`,"Notion-Version":NOTION_VERSION,"Content-Type":"application/json"},body:JSON.stringify({properties})}),d=await r.json();if(!r.ok)throw new Error(d.message||"Notion rejected update");return d}

async function discordRegistration(env,name,beforeIds,afterIds,eventRows){if(!env.DISCORD_WEBHOOK_URL)return;try{const before=new Set(beforeIds||[]),after=new Set(afterIds||[]),eventMap=new Map(eventRows.map(e=>[e.id,e.properties?.Event||"Unknown event"])),added=[...after].filter(id=>!before.has(id)).map(id=>eventMap.get(id)||"Unknown event"),removed=[...before].filter(id=>!after.has(id)).map(id=>eventMap.get(id)||"Unknown event");let content;if(before.size===0&&after.size>0){content=`🎉 **New registration — ${name}**\nRegistered for ${after.size} event${after.size===1?"":"s"}.\n${[...after].map(id=>`• ${eventMap.get(id)||"Unknown event"}`).join("\n")}`}else if(after.size===0&&before.size>0){content=`⚠️ **Registration cleared — ${name}**\nRemoved all event registrations.\n${removed.map(x=>`− ${x}`).join("\n")}`}else if(added.length||removed.length){content=`🔄 **Registration changed — ${name}**${added.length?`\n${added.map(x=>`+ ${x}`).join("\n")}`:""}${removed.length?`\n${removed.map(x=>`− ${x}`).join("\n")}`:""}`}else{return}await fetch(env.DISCORD_WEBHOOK_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})})}catch(e){console.error("Discord registration notification failed",e)}}
function standings(rows){const t=Object.fromEntries(TEAMS.map(x=>[x,0]));for(const r of rows){const p=r.properties||{};for(const x of teams(p["🥇 Team"]))t[x]+=num(p["🥇 Gold Points"]);for(const x of teams(p["🥈 Team"]))t[x]+=num(p["🥈 Silver Points"]);for(const x of teams(p["🥉 Team"]))t[x]+=num(p["🥉 Bronze Points"])}return TEAMS.map(team=>({team,points:t[team]})).sort((a,b)=>b.points-a.points)}
async function scores(env){if(!env.NOTION_API_TOKEN)return json({configured:false,error:"NOTION_API_TOKEN is missing in Cloudflare."},{status:503});try{const rows=(await queryAll(env.NOTION_API_TOKEN,ds(env.NOTION_DATA_SOURCE_ID))).map(page),s=standings(rows),remaining=rows.filter(r=>!complete(r)).reduce((a,r)=>a+num(r.properties?.["🥇 Gold Points"]),0);return json({configured:true,standings:s,race:{completedEvents:rows.filter(complete).length,totalEvents:rows.length,remainingGoldPoints:remaining,maximumPossible:s.map(x=>({team:x.team,currentPoints:x.points,maximumPoints:x.points+remaining}))},rows,updatedAt:new Date().toISOString()})}catch(e){return json({error:e.message},{status:502})}}

async function registration(request,env){if(!env.NOTION_API_TOKEN)return json({error:"Registration is not connected to Notion."},{status:503});const eventId=ds(env.NOTION_DATA_SOURCE_ID);if(request.method==="GET"){try{const[ps,es]=await Promise.all([queryAll(env.NOTION_API_TOKEN,PARTICIPANTS_ID),queryAll(env.NOTION_API_TOKEN,eventId)]);return json({participants:ps.map(page).map(x=>({id:x.id,name:x.properties.Participant,divisions:x.properties.Division||[],registeredEventIds:x.properties["Registered Events"]||[]})).sort((a,b)=>a.name.localeCompare(b.name)),events:es.map(page).map(x=>({id:x.id,name:x.properties.Event,number:x.properties["Event #"],divisions:x.properties["Division 2"]||[],format:x.properties.Format})).sort((a,b)=>num(a.number)-num(b.number))})}catch(e){return json({error:e.message},{status:502})}}if(request.method==="POST"){try{const b=await request.json(),pid=String(b.participantId||""),wanted=[...new Set(Array.isArray(b.eventIds)?b.eventIds.map(String):[])];const[ps,es]=await Promise.all([queryAll(env.NOTION_API_TOKEN,PARTICIPANTS_ID),queryAll(env.NOTION_API_TOKEN,eventId)]),participantRows=ps.map(page),eventRows=es.map(page),p=participantRows.find(x=>x.id===pid);if(!p)return json({error:"Participant not found."},{status:404});const map={Man:"Men",Woman:"Women",Kid:"Kids"},pd=p.properties.Division||[],eligible=new Set(eventRows.filter(e=>pd.some(d=>(e.properties["Division 2"]||[]).includes(map[d])||(e.properties["Division 2"]||[]).includes("Both"))).map(e=>e.id));if(wanted.some(id=>!eligible.has(id)))return json({error:"One or more selected events are not eligible for this participant."},{status:400});const before=p.properties["Registered Events"]||[];await patch(pid,{"Registered Events":{relation:wanted.map(id=>({id}))}},env);await discordRegistration(env,p.properties.Participant||"Unknown participant",before,wanted,eventRows);return json({ok:true,eventIds:wanted})}catch(e){return json({error:e.message},{status:400})}}return json({error:"Method not allowed"},{status:405})}

async function fillCornholeSlot(rows,code,team,players,env){if(!code||code.includes("if needed")||!team)return;const target=rows.find(x=>x.properties.Match===code);if(!target)return;const p=target.properties,props={};if(!p["Team A"]){props["Team A"]=rt(team);props["Team A Players"]=rt(players);p["Team A"]=team;p["Team A Players"]=players}else if(!p["Team B"]&&p["Team A"]!==team){props["Team B"]=rt(team);props["Team B Players"]=rt(players);p["Team B"]=team;p["Team B Players"]=players}else return;if(p["Team A"]&&p["Team B"]){props.Status={select:{name:"Ready"}};p.Status="Ready"}await patch(target.id,props,env)}
async function resolveOpeningByes(rows,env){const opening=rows.filter(m=>m.properties.Bracket==="Winners"&&num(m.properties.Round)===1).sort((a,b)=>num(a.properties["Sort Order"])-num(b.properties["Sort Order"]));for(const m of opening){const p=m.properties;if(p.Status==="Complete")continue;const a=String(p["Team A"]||""),b=String(p["Team B"]||"");if(Boolean(a)===Boolean(b))continue;const winner=a||b,winnerPlayers=a?String(p["Team A Players"]||""):String(p["Team B Players"]||"");await patch(m.id,{"Score A":{number:null},"Score B":{number:null},Winner:rt(winner),Loser:rt(""),Status:{select:{name:"Complete"}}},env);p["Score A"]=null;p["Score B"]=null;p.Winner=winner;p.Loser="";p.Status="Complete";p.Bye=true;await fillCornholeSlot(rows,p["Winner To"],winner,winnerPlayers,env)}}
async function cornhole(request,env){if(!env.NOTION_API_TOKEN)return json({error:"Cornhole bracket is not connected to Notion."},{status:503});try{if(request.method==="GET"){const rows=(await queryAll(env.NOTION_API_TOKEN,CORNHOLE_ID)).map(page).sort((a,b)=>num(a.properties["Sort Order"])-num(b.properties["Sort Order"]));await resolveOpeningByes(rows,env);return json({matches:rows,updatedAt:new Date().toISOString()})}if(request.method==="POST"){const b=await request.json(),rows=(await queryAll(env.NOTION_API_TOKEN,CORNHOLE_ID)).map(page),m=rows.find(x=>x.id===String(b.matchId||""));if(!m)return json({error:"Match not found."},{status:404});const a=String(b.teamA||m.properties["Team A"]||""),bb=String(b.teamB||m.properties["Team B"]||""),ap=String(b.teamAPlayers||m.properties["Team A Players"]||""),bp=String(b.teamBPlayers||m.properties["Team B Players"]||""),sa=Number(b.scoreA),sb=Number(b.scoreB);if(!a||!bb||!Number.isFinite(sa)||!Number.isFinite(sb)||sa===sb)return json({error:"Enter both teams and a non-tied score."},{status:400});const winner=sa>sb?a:bb,loser=sa>sb?bb:a,wPlayers=sa>sb?ap:bp,lPlayers=sa>sb?bp:ap;await patch(m.id,{"Score A":{number:sa},"Score B":{number:sb},Winner:rt(winner),Loser:rt(loser),Status:{select:{name:"Complete"}}},env);m.properties["Score A"]=sa;m.properties["Score B"]=sb;m.properties.Winner=winner;m.properties.Loser=loser;m.properties.Status="Complete";await fillCornholeSlot(rows,m.properties["Winner To"],winner,wPlayers,env);await fillCornholeSlot(rows,m.properties["Loser To"],loser,lPlayers,env);return json({ok:true,winner,loser})}return json({error:"Method not allowed"},{status:405})}catch(e){return json({error:e.message},{status:502})}}

async function admin(request,env){if(!env.NOTION_API_TOKEN||!env.ADMIN_SCORE_CODE)return json({error:"Score entry runtime secrets are missing."},{status:503});let b;try{b=await request.json()}catch{return json({error:"Invalid request."},{status:400})}if(String(b.code||"")!==String(env.ADMIN_SCORE_CODE))return json({error:"Incorrect score-entry code."},{status:401});const id=String(b.eventId||"");if(!id)return json({error:"Choose an event."},{status:400});try{if(b.action==="clear"){await patch(id,{"🥇 Team":{multi_select:[]},"🥈 Team":{multi_select:[]},"🥉 Team":{multi_select:[]},Status:{status:{name:"Not Started"}}},env);return json({ok:true,cleared:true})}const gold=teams(b.goldTeams??b.goldTeam),silver=teams(b.silverTeams??b.silverTeam),bronze=teams(b.bronzeTeams),two=Boolean(b.isTwoTeam),status=EVENT_STATUSES.includes(b.status)?b.status:"Complete";if(!gold.length||!silver.length)return json({error:"Choose gold and silver teams."},{status:400});if(gold.length>(two?2:1)||silver.length>(two?2:1)||two&&(gold.length!==2||silver.length!==2||bronze.length))return json({error:two?"Two-team events require exactly two Gold teams, two Silver teams, and no Bronze teams.":"Normal events use one Gold team and one Silver team."},{status:400});if(new Set([...gold,...silver,...bronze]).size!==gold.length+silver.length+bronze.length)return json({error:"A team cannot occupy more than one finishing position."},{status:400});await patch(id,{"🥇 Team":{multi_select:gold.map(name=>({name}))},"🥈 Team":{multi_select:silver.map(name=>({name}))},"🥉 Team":{multi_select:bronze.map(name=>({name}))},Status:{status:{name:status}}},env);return json({ok:true,status})}catch(e){return json({error:e.message},{status:502})}}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==="/api/scores")return request.method==="GET"?scores(env):json({error:"Method not allowed"},{status:405});if(u.pathname==="/api/registration")return registration(request,env);if(u.pathname==="/api/cornhole")return cornhole(request,env);if(u.pathname==="/api/admin/scores")return request.method==="POST"?admin(request,env):json({error:"Method not allowed"},{status:405});if(u.pathname.startsWith("/api/"))return json({error:"Not found"},{status:404});return env.ASSETS?env.ASSETS.fetch(request):new Response("Not found",{status:404})}};